# Basic options
title: Deepa Rao, PhD
author:
  name: Deepa Rao
  email: drao@mit.edu
description: Computational Ecologist
url: "https://deepa-rao.github.io/"
github_username: deepa-rao

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
#remote_theme: owner/name
#remote_theme: poole/hyde

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Format of the permalinks
permalink:             /:year/:month/:day/:title/

# Siderbar order
defaults:
  - scope:
      path: README.md
    values:
      menu: true
      order: 1
  - scope:
      path: about.md
    values:
      menu: true
      order: 2
  - scope:
      path: data-science.md
    values:
      menu: true
      order: 3
