# Basic options
title: Deepa Rao, PhD
author:
  name: Deepa Rao
  email: drao@mit.edu
description: Computational Ecologist
url: "https://deepa-rao.github.io/"
github_username: deepa-rao

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

